---
title: "Model 119 (testing)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      cache = TRUE,
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

# ## clean the R environment
# graphics.off()
# rm(list = ls())
# freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(plyr)
library(JMbayes2, quietly = TRUE)
devtools::load_all()

## check the directory for the file
# here::dr_here()
here::set_here()

```

```{css, "css-setup", echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## To-do list

-   [x] Change `bmi` into categorical variable

-   [x] Prediction based on the testing dataset

-   [x] AUCs and Brier Scores

-   [x] `r praise::praise()`

## Loading data and merge variables

```{r}
load("data/test_amh0.rda")
load("data/test_amh1.rda")

test_amh01 <- test_amh0 %>%
  mutate(site = case_when(site == "11" ~ "M",
                          site == "12" ~ "B",
                          site =="13" ~ "C",
                          site =="14" ~ "UCD",
                          site =="15" ~ "UCLA",
                          site =="16" ~ "NJ",
                          site =="17" ~ "P"),
         lamh = log(amh),
         ethnic = factor(ethnic, levels = c("CAUCA", "BLACK",
                                            "CHINE", "HISPA",
                                            "JAPAN")),
         bmi_cat = as.factor(bmi_cat),
         # site = factor(site, levels = c("B", "C", "M",
         #                                "NJ", "P",
         #                                "UCD", "UCLA")),
         smoke = factor(smoke, levels = c("Never Smoked" ,
                                          "Past Only",
                                          "Current Smoker"))) %>% 
  cbind(model.matrix(~ 1 + site + ethnic + smoke,
                     data = .)) %>%
  janitor::clean_names() %>%
  dplyr::select(-intercept) %>%
  dplyr::select(order(colnames(.))) %>% 
  filter(!is.na(time), 
         !is.na(amh))

```

## Value + Rate model

$$
\begin{split}
  jmb2.119.value.rate: & \\ 
  lme1: \ \ \  & \pmb m(time) = (fixed = lamh \sim time,\\
  & \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \  random = time| id) \\
  surv19: \ \ \ & Surv(etime, event) \sim  factor(bmi) + site + ethnic + smoke \\
  & \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ + \pmb m(time) + \pmb m'(time) 
\end{split}
$$

```{r}
load("results/jmb2_119_chain5_it100k_thin100_total5k.Rdata")
summary(jmb2.119.value.rate)

pred1 <- predict(jmb2.119.value.rate, 
                 newdata = test_amh01,
                 process = "longitudinal",
                 type = "mean_subject",
                 return_newdata = FALSE)
# test_amh01$pred <- unlist(pred1$preds)
margin_data <- cbind(time = test_amh01$time, 
                     lamh = pred1$preds$lamh) %>% 
  as.data.frame() %>% 
  unique() %>% 
  as.data.frame() %>%
  arrange(time)

# swan_amh03 <- na.omit(swan_amh03) %>%
#   group_by(id) %>%
#   arrange(time)
pred2 <- predict(jmb2.119.value.rate,
                 newdata = swan_amh03,
                 process = "longitudinal",
                 type = "mean_subject",
                 return_newdata = FALSE)
# swan_amh03$pred <- unlist(pred2$preds)
# swan_amh03
```

## AUC

```{r}
#| label: "auc_value_rate"
#| warning: false
#| eval: false

set.seed(7732)
AUC2_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 2,
                                      Dt = .x)))

AUC3_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 3,
                                      Dt = .x)))
AUC4_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 4,
                                      Dt = .x)))
AUC5_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 5,
                                      Dt = .x)))
AUC6_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 6,
                                      Dt = .x)))
AUC8_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvAUC(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 8,
                                      Dt = .x)))

Tstart2_test = map(AUC2_test, "auc") %>% as.character()
Tstart3_test = map(AUC3_test, "auc") %>% as.character()
Tstart4_test = map(AUC4_test, "auc") %>% as.character()
Tstart5_test = map(AUC5_test, "auc") %>% as.character()
Tstart6_test = map(AUC6_test, "auc") %>% as.character()
Tstart8_test = map(AUC8_test, "auc") %>% as.character()

tbl_auc_value_rate_test <- rbind(Tstart2_test, 
                            Tstart3_test,
                            Tstart4_test,
                            Tstart5_test,
                            Tstart6_test, 
                            Tstart8_test) %>% 
  as.data.frame() %>%
  mutate_all(as.numeric) %>%
  round(4)

names(tbl_auc_value_rate_test) <- c("Dt1", "Dt2", "Dt3", "Dt4", "Dt5")

save(AUC2_test, AUC3_test, 
     AUC4_test, AUC5_test,
     AUC6_test, AUC8_test, 
     tbl_auc_value_rate_test,
     file = paste0("results/new_jmb2_119_test_auc_chain5_it1000k_thin100_total5k.Rdata"))
```

## Brier Scores

```{r}
#| label: "bs_table_value_rate"
#| warning: false
#| eval: false

Brier2_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 2,
                                      Dt = .x)))
Brier3_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 3,
                                      Dt = .x)))
Brier4_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 4,
                                      Dt = .x)))
Brier5_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 5,
                                      Dt = .x)))
Brier6_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 6,
                                      Dt = .x)))
Brier8_test  <- map(c(1, 2, 3, 4, 5), 
                 ~try(JMbayes2::tvBrier(jmb2.119.value.rate,
                                      test_amh01,
                                      Tstart = 8,
                                      Dt = .x)))

Tstart2_test = map(Brier2_test, "Brier") %>% as.character()
Tstart3_test = map(Brier3_test, "Brier") %>% as.character()
Tstart4_test = map(Brier4_test, "Brier") %>% as.character()
Tstart5_test = map(Brier5_test, "Brier") %>% as.character()
Tstart6_test = map(Brier6_test, "Brier") %>% as.character()
Tstart8_test = map(Brier8_test, "Brier") %>% as.character()

tbl_bs_value_rate_test <- rbind(Tstart2_test,
                Tstart3_test,
                Tstart4_test,
                Tstart5_test,
                Tstart6_test,
                Tstart8_test) %>% 
  as.data.frame() %>%
  mutate_all(as.numeric) %>%
  round(4)

names(tbl_bs_value_rate_test) <- c("Dt1", "Dt2", "Dt3", "Dt4", "Dt5")
save(Brier2_test, Brier3_test,
     Brier4_test, Brier5_test,
     Brier6_test, Brier8_test,
     tbl_bs_value_rate_test,
     file = paste0("results/jmb2_119_test_brier_chain5_it60k_thin100_total3k.Rdata"))

```

```{r}
#| label: "bs_value_rate"

load("results/jmb2_119_test_brier_chain5_it500k_thin50_total50k.Rdata")
tbl_bs_value_rate_test %>% knitr::kable()
```
