# Working log {.unnumbered}

## 20240401

-   [x] Merge the site and ethnicity into 14 level factor

-   [x] Age is not the variable into the model; remove it, the age is already registered, with age all started from 42

-   [x] Linear and quadratic terms for rate model $m'(t)$

-   [x] Compare the linear & quadratic terms without the rate model

-   [x] With rate for linear and quadratic get rid of the quadratic term first.

-   [x] Should we include interaction terms??? (the team already decided to what included into the model)

## 20240405

-   [x] Test if taking out all CATegorical vars you are able to do a specific dynamic prediction (for a given pat)

-   [x] Combine site and ethnicity variables into a single var with 14 levels,

-   [x] Compare models with and without rate in the survival model

-   [x] AUC, ROC, and Brier Score... It is possible to calculate AUC and brier score for the entire dataset

## 20240408

-   [x] Test different time slope (rate) model in the survival model

-   [x] Test linear and quadratic terms model in the survival model

## 20240410

-   [x] ask about the interaction terms $m(t)$ and $m'(t)$ with other variables

-   [x] whether we need to separate the `site` and `ethnicity`

-   [x] add age mfp median and range and IQR **event time** for

-   [o] change the time for the plots into real age.

-   [x] dummy variables into the site and ethnicity

-   [x] rerun the model without the rate model

-  [x] provide the AUC and ROC for 2, 3, 4, 5, 6, and 8 years

## 20240412

- [x] provide the AUC and ROC for `Tstart` 2, 3, 4, 5, 6, and 8 years

- [x] provide the `Dt` for 2, 3, 4, and 5 years

- [x] file `10_final_model.Rmd` is the final model

- [x] run the final model in a longer chain (ask EJC about the computer)

## 20240417

- [x] check email and file the disclosure for the abstract

- [x] model selection for jm model backward 

- [x] add the joint model with rate and baseline

- [x] compare joint model with rate and value.








